### ISSUE TITLE
Mozmill-Crowd stalls at Starting Download on OSX

### ISSUE THREAD

**Issue by bkerensa** [whimboo/mozmill-crowd#22]
On today's nightly on Yosemite 10.10 Mozmill-Crowd stalls at Starting Download and never completes

**Comment by whimboo** [comment]
This looks to be the same problem as for https://bugzilla.mozilla.org/show_bug.cgi?id=1112527. We make use of `saveURI` here too to store the downloaded environment. So the same patch would be necessary. 

https://github.com/whimboo/mozmill-crowd/blob/master/extension/chrome/content/download.js#L97

It sounds easy enough to fix, so we could get a new version out soon. Thanks for reporting this @bkerensa.

**Comment by whimboo** [comment]
PR #23 has been merged. Thanks Cosmin.
